spring:
  data:
    redis:
      host: ${REDIS_LOCAL_HOST_NAME}
      port: ${REDIS_LOCAL_PORT}

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

  config:
    import: classpath:application-key.yml

  kafka:
    bootstrap-servers: ${KAFKA_DEV_URL}
    consumer:
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: '*'
    topic:
      queue-alarm-event: queue-alarm-event-topic
      reservation-create-event: reservation-create-event-topic
      reservation-update-event: reservation-update-event-topic
      queue-reservation-event: queue-reservation-event-topic

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19000/eureka/

server:
  port: 19030
